name: pan_scrapper
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.1
  flutter_inappwebview: 6.1.5
  dio: 5.9.0
  crypto: ^3.0.0
  html: ^0.15.6
  dio_cookie_manager: ^3.3.0
  cookie_jar: ^4.0.8
  validate_rut: ^0.2.2
  cached_network_svg_image: ^1.2.0
  animations: ^2.1.1
  currency_formatter: ^2.2.0
  json_annotation: ^4.9.0
  flutter_secure_storage: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
